### ISSUE TITLE
Porting sc3 apps lib error

### ISSUE THREAD

**Issue by braunfuss** [SeisComP/seiscomp#18]
Trying to port the mags-detector app (https://github.com/SeisComP3/bgr-mags-addons) from sc3 to sc4 i encountered the issue during build that the include of libs
does not work, even after exchanging the prefix seiscomp3 to the general seiscomp, e.g. 

fatal error: seiscomp/client/streamapplication.h: No such file or directory
 #include <seiscomp/client/streamapplication.h>

What is the preferred way of handling the old includes (i see they are still in repo) or how do i make the env aware of the lib paths.

best and thanks,
Andreas

**Comment by jsaul** [comment]
In the `src` directory there is a subdirectory `extras`. This is where you move your `bgr-mags-addons` directory to so that the source code will be in `src/extras/bgr-mags-addons`. As you already have adapted the include files you can immediately compile it (while keeping your fingers crossed!). It may work out of the box, but also may require further adaptions.

It would be great if the project can be 'officially' upgraded to SeisComP 4.

**Comment by braunfuss** [comment]
Thank you, that worked and compiled correctly, some changes were necessary. I will create a sc4 branch of the mags detector and make a pull request in due time after testing. 

Best and thanks,
Andreas

**Comment by jsaul** [comment]
Glad it worked so painlessly. Looking forward to your new branch, Thanks for your efforts!
