### ISSUE TITLE
Using Git submodule

### ISSUE THREAD

**Issue by morealaz** [SeisComP/seiscomp#31]
Why aren't this project using `git sublodule` for sub-projects like seedlink and other modules that are required for compiling `seiscomp`?

https://git-scm.com/book/en/v2/Git-Tools-Submodules
https://git-scm.com/docs/gitsubmodules
https://git-scm.com/docs/git-submodule

**Comment by gempa-jabe** [comment]
We have considered this option in the beginning and we found that mounting sub projects manually gives us more flexibility and is also easy to work with. Using [mu](https://fabioz.github.io/mu-repo/) helps us easing this task even more without the hassles with submodules. Maybe things have changed, maybe we were not able to get comfortable with submodules, maybe we like mu. We haven't had a moment when we regretted the use of mutli repos instead of submodules over the past years. The team feels comfortable with it and that is actually what is important.

Btw, seedlink is not required to compile seiscomp. It is an optional component which is shipped by default with the distribution.

I hope that explains it for you. If you have suggestions, we are happy to discuss them.

**Comment by morealaz** [comment]
```mermaid
classDiagram
Class01 <|-- AveryLongClass : Cool
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 --> C2 : Where am i?
Class09 --* C3
Class09 --|> Class07
Class07 : equals()
Class07 : Object[] elementData
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
Class08 <--> C2: Cool label
```
