### ISSUE TITLE
scmaster not installing on build from source

### ISSUE THREAD

**Issue by rwalkerlewis** [SeisComP/seiscomp#47]
Building from source on several docker environments for Ubuntu 18.04, 20.04, 22.04, as well as a personal laptop for 22.04, the latest pull of the SeisComP source (using the script in the readme for the seiscomp repository) configures using cmake, makes, but upon run of make install, the following error results:

```
CMake Error at src/base/common/apps/messaging/scmaster/cmake_install.cmake:52 (file):
  file INSTALL cannot find "/home/dockimble/projects/seiscomp/bin/scmaster":
  No such file or directory.
Call Stack (most recent call first):
  src/base/common/apps/messaging/cmake_install.cmake:47 (include)
  src/base/common/apps/cmake_install.cmake:63 (include)
  src/base/common/cmake_install.cmake:47 (include)
  src/base/cmake_install.cmake:48 (include)
  src/cmake_install.cmake:48 (include)
  cmake_install.cmake:55 (include)
```
Upon inspection of the bin directory at the install location, scmaster is not present.

**Comment by gempa-jabe** [comment]
You should not build in the source tree. From your small log excerpt I see that you created the build files not within a dedicated build directory.  I have created a fresh build and scmaster is present. You can check if the option `SC_TRUNK_MASTER` is OFF in your configuration. Otherwise the binary must be present.

**Comment by rwalkerlewis** [comment]
Changed the build directory to one different from the install prefix, resolving the issue. Thank you.
